- name: Run a play using the collections keyword
  hosts: win
  collections:
    - ansible.windows
  tasks:
    - name: Run a module not specifying FQCN
      my_module: win_firewall
        state: enabled    