- name: Windows Firewall
  hosts: win
  become: true
  tasks:
    - name: Enable firewall for Private profiles
      win_firewall:
        state: enabled
        profiles:
        - Private
      tags: enable_firewall