- name: Run a play using the collections keyword
  hosts: windows
  tasks:
  - name: Enable firewall for Domain, Public and Private profiles
    ansible.windows.win_firewall:
      state: enabled
      profiles:
        - Public
    tags: enable_firewall
