- name: Run a play using the collections keyword
  hosts: win
  collections:
    - ansible.windows
  tasks:
    - name: Run a module not specifying FQCN
      my_module: 
        option1: win_firewall   