- name: Hostname Change
  hosts: windows
  remote_user: Administrator
  gather_facts: True
  tasks:
  - name: Change the hostname to sample-hostname
    ansible.windows.win_hostname:
      name: win-host-1
    register: res

  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required
